service: shibamanga

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  environment:
    ELASTICSEARCH_HOST: ${env:ELASTICSEARCH_HOST}
    ELASTICSEARCH_INDEX: shibamanga

functions:
  1getManga:
    handler: handler.getManga
    events:
      - http:
          path: api/manga/{mangaid}
          method: get
          request:
            parameters:
              querystrings:
                source: true
  2getChapter:
    handler: handler.getChapter
    events:
      - http:
          path: api/manga/{mangaid}/{chapternum}
          method: get
          request:
            parameters:
              querystrings:
                source: true
  3searchMangas:
    handler: handler.searchMangas
    events:
      - http:
          path: api/search
          method: get
          request:
            parameters:
              querystrings:
                page: true
                length: true
                query: true
  4getRecommendations:
    handler: handler.getRecommendations
    events:
      - http:
          path: api/recommendations
          method: get
          request:
            parameters:
              querystrings:
                page: true
                length: true
  5getReleases:
    handler: handler.getReleases
    events:
      - http:
          path: api/releases
          method: get
          request:
            parameters:
              querystrings:
                page: true
                length: true
  6getPopular:
    handler: handler.getPopular
    events:
      - http:
          path: api/popular
          method: get
          request:
            parameters:
              querystrings:
                page: true
                length: true
                not_ids: true
  7getList:
    handler: handler.getList
    events:
      - http:
          path: api/list
          method: get
          request:
            parameters:
              querystrings:
                ids: true
  8getGenre:
    handler: handler.getGenre
    events:
      - http:
          path: api/genre
          method: get
          request:
            parameters:
              querystrings:
                genre: true
                page: true
                length: true
                not_ids: true
  9updateMangas:
    handler: handler.updateMangas
    events:
      - http:
          path: updater/mangas
          method: get
  10updateMangasources:
    handler: handler.updateMangasources
    events:
      - schedule: rate(1 day)
  11updateReleases:
    handler: handler.updateReleases
    events:
      - schedule: rate(1 hour)

plugins:
  - serverless-webpack

#custom:
#  webpackIncludeModules: true # enable auto-packing of external modules