service: shibamanga

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-central-1
  environment:
    ELASTICSEACH_HOST: url
    ELASTICSEACH_INDEX: shibamanga

functions:
  getManga:
    handler: handler.getManga
    events:
      - http:
          path: api/manga/{mangaid}
          method: get
          request:
            parameters:
              querystrings:
                source: true
  getChapter:
    handler: handler.getChapter
    events:
      - http:
          path: api/manga/{mangaid}/{chapternum}
          method: get
          request:
            parameters:
              querystrings:
                source: true
  searchMangas:
    handler: handler.searchMangas
    events:
      - http:
          path: api/search
          method: get
          request:
            parameters:
              querystrings:
                page: true
                length: true
                query: true
  getRecommendations:
    handler: handler.getRecommendations
    events:
      - http:
          path: api/recommendations
          method: get
          request:
            parameters:
              querystrings:
                page: true
                length: true
  getReleases:
    handler: handler.getReleases
    events:
      - http:
          path: api/releases
          method: get
          request:
            parameters:
              querystrings:
                page: true
                length: true
  getPopular:
    handler: handler.getPopular
    events:
      - http:
          path: api/popular
          method: get
          request:
            parameters:
              querystrings:
                page: true
                length: true
                not_ids: true
  getList:
    handler: handler.getList
    events:
      - http:
          path: api/list
          method: get
          request:
            parameters:
              querystrings:
                ids: true
  getGenre:
    handler: handler.getGenre
    events:
      - http:
          path: api/genre
          method: get
          request:
            parameters:
              querystrings:
                genre: true
                page: true
                length: true
                not_ids: true
  updateMangas:
    handler: handler.updateMangas
    events:
      - http:
          path: updater/mangas
          method: get
  updateMangasources:
    handler: handler.updateMangasources
    events:
      - schedule: rate(1 day)
  updateReleases:
    handler: handler.updateReleases
    events:
      - schedule: rate(1 hour)

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true # enable auto-packing of external modules