service: sources

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-central-1
  environment:
    elasticsearch: search-shibamanga-cajawfcxg7o3ay5rr4kzh43h4m.eu-central-1.es.amazonaws.com

functions:
  updateMangas:
    handler: handler.updateMangas
    events:
      - http:
          path: updater/mangas
          method: get
  updateMangasources:
    handler: handler.updateMangasources
    events:
      - schedule: rate(1 day)
  updateReleases:
    handler: handler.updateReleases
    events:
      - schedule: rate(1 hour)

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true # enable auto-packing of external modules